name: test

on:
  push:
    branches: ["main"]

jobs:
  test:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -el {0}

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          environment-file: env.yml
          init-shell: bash
          cache-environment: true
          post-cleanup: "all"

      - name: init playwright
        run: playwright install

      - name: run pytest
        run: pytest
