name: test

on:
  push:
    branches: ["test-ci"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: mamba-org/setup-micromamba@v2
        with:
          environment-name: test-env
          environment-file: env.yml
          init-shell: bash
          cache-environment: true
          post-cleanup: "all"
      - name: run in bash
        run: python --version && pytest --version
        shell: bash -el {0}
